/**:
  ros__parameters:
    camera:
      model: Pinhole
      width: 640
      height: 480
      scale: 1.0

      fx: 519.9396058487
      fy: 518.3656543383
      cx: 316.4675557042
      cy: 235.9021996274

      d0: 0.000000002
      d1: -0.00000001
      d2: 0.0
      d3: 0.0

#错误内参
# /**:
#   ros__parameters:
#     camera:
#       model: Pinhole
#       width: 640
#       height: 480
#       scale: 1.0

#       fx: 541.76029
#       fy: 542.76967
#       cx: 320.29905
#       cy: 239.39939

#       d0: 0.029954
#       d1: -0.067090
#       d2: 0.004992
#       d3: -0.004979

# /**:
#   ros__parameters:
#     camera:
#       model: Pinhole
#       width: 640
#       height: 480
#       # 缩放因子，通常保持 1.0
#       scale: 1.0
#       # 内参矩阵数据
#       fx: 524.469
#       fy: 526.238
#       cx: 314.044
#       cy: 249.519
#       # 畸变系数 (k1, k2, p1, p2)
#       d0: 0.009512
#       d1: 0.000001
#       d2: 0.006974
#       d3: 0.000202

# /**:
#   ros__parameters:
#     camera:
#       model: Pinhole
#       width: 3840
#       height: 2160
#       scale: 0.5
#       fx: 2702.98
#       fy: 2700.39
#       cx: 2015.11
#       cy: 878.109
#       d0: -0.076160
#       d1: 0.123001
#       d2: -0.00113
#       d3: 0.000251
      
