/**:
  ros__parameters:
    camera:
      model: Pinhole
      width: 3840
      height: 2160
      scale: 0.5
      fx: 2702.98
      fy: 2700.39
      cx: 2015.11
      cy: 878.109
      d0: -0.076160
      d1: 0.123001
      d2: -0.00113
      d3: 0.000251
      
