/**:
  ros__parameters:
    "mamba_pose/enabled": true
    "mamba_pose/backend_type": "onnx"
    "mamba_pose/model_path": "/home/liu/fast_livo2/src/FAST-LIVO2/Log/models/oversized_mamba_pose.onnx"
    "mamba_pose/onnx_input_name": "input"
    "mamba_pose/onnx_output_name": "output"
    "mamba_pose/use_cpu_inference": true
    "mamba_pose/history_len": 10
    "mamba_pose/min_ready_frames": 3
    "mamba_pose/debug_log_en": true

    "mamba_pose/max_rotation_correction_rad": 0.10
    "mamba_pose/max_translation_correction_m": 0.20
    "mamba_pose/reject_non_finite_output": true
    "mamba_pose/reject_oversized_output": false

    "mamba_pose/export_train_data_en": false
    "mamba_pose/export_train_data_path": "/home/liu/fast_livo2/src/FAST-LIVO2/Log/mamba_pose_train_data.csv"
